[package]
name = "inori"
version = "0.2.5"
edition = "2021"
rust-version = "1.82"
authors = ["esrh <esrh@esrh.me>"]
description = "mpd client"
homepage = "https://github.com/eshrh/inori"
repository = "https://github.com/eshrh/inori"
license = "GPL-3.0-only"
readme = "README.md"
keywords = ["mpd", "music"]
categories = ["command-line-utilities", "multimedia", "multimedia::audio"]

[lints.rust]
unsafe_code = "forbid"

[dependencies]
ratatui = { version = "0.30.0-alpha.5", features = ["serde"] }
nucleo-matcher = "0.3.1"
itertools = "0.14.0"
bitflags = "2.6.0"
toml = "0.8.19"
serde = "1.0.225"
platform-dirs = "0.3.0"

[dependencies.mpd]
version = "0.2.2"
package = "inori-mpd"
